/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiValidationError } from './apiValidationError';
import { InnerError } from './innerError';

export interface ErrorResponse {
  status?: number;
  error?: string | ErrorResponse;
  message?: string;
  path?: string;
  timestamp?: string;
  innerError?: InnerError;
  subErrors?: Array<ApiValidationError>;
}
