/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';
import { Storage } from '../storage';
import { Obligation } from '../obligation';
import { ProcessingBasisLegalBasisEnum, ProcessingBasisProcessingCategoriesEnum, ProcessingBasisRecipientsEnum } from '../processingBasis';
import { Organization } from '../service-link/organization';

export interface UsageRules {
  purposeId: string;
  purposeCategory: string;
  legalBasis: ProcessingBasisLegalBasisEnum;
  purposeName: string;
  processingCategories: Array<ProcessingBasisProcessingCategoriesEnum>;
  policy: Policy;
  storage?: Storage;
  recipients?: Array<ProcessingBasisRecipientsEnum>;
  shareWith?: Array<Organization>;
  obligations?: Array<Obligation>;
  collectionMethod?: string;
  termination?: string;
}
