FROM ubuntu:24.04
WORKDIR /app
COPY . .
RUN ["tar", "-xzf", "jdk-16.0.2_linux-x64_bin.tar.gz", "-C", "/usr/local/"]
ENV JAVA_HOME=/usr/local/jdk-16.0.2
ENV PATH="$JAVA_HOME/bin:${PATH}"


CMD ["bash"]
