/**
 * CaPe API - Account Manager
 * CaPe APIs used to manage CaPe Account, Service Link Records and Service Linking internal operations
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceLinkRecordDoubleSigned } from '../service-linking/serviceLinkRecordDoubleSigned';
import { EventLog, AuditLog } from '../auditlogs/auditlogs.model';
import { ConsentRecordSigned } from '../consents/consentRecordSigned';
import { AccountInfo } from './account.model';


export interface AccountExport {
  accountInfo?: AccountInfo;
  serviceLinks?: Array<ServiceLinkRecordDoubleSigned>;
  consentRecords?: Array<ConsentRecordSigned>;
  eventLogs?: Array<EventLog>;
  auditLog?: AuditLog;
}

