version: "3.8"
services:
  cape-service-editor:
    image: capesuite/cape-service-editor:latest
    build:
      context: .
      args:
        BASE_HREF: /cape-service-editor
    ports:
      - "81:80"
    volumes:
      - ./src/assets/config.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cape-network


networks:
 cape-network:
   name: cape-service-editor-network
   driver: bridge
   driver_opts:
     com.docker.network.driver.mtu: 1400
