/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsentNotarizationPart } from './consentNotarizationPart';
import { CommonPart } from './commonPart';
import { ConsentRecordRoleSpecificPart } from './consentRecordRoleSpecificPart';

export interface ConsentRecordPayload {
  consentNotarization?: ConsentNotarizationPart;
  common_part?: CommonPart;
  role_specific_part?: ConsentRecordRoleSpecificPart;
}
