/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyType } from './keyType';
import { KeyUse } from './keyUse';
import { Algorithm } from './algorithm';
import { JWKKeyStore } from './jWKKeyStore';
import { JWKParsedX509CertChain } from './jWKParsedX509CertChain';

export interface JWK {
  keyStore?: JWKKeyStore;
  _private?: boolean;
  algorithm?: Algorithm;
  keyID?: string;
  keyType?: KeyType;
  keyUse?: KeyUse;
  keyOperations?: Array<KeyOperationsEnum>;
  x509CertURL?: string;
  x509CertChain?: Array<unknown>;
  parsedX509CertChain?: Array<JWKParsedX509CertChain>;
  requiredParams?: { [key: string]: unknown };
  x509CertThumbprint?: unknown;
  x509CertSHA256Thumbprint?: unknown;
}
export enum KeyOperationsEnum {
  Sign = 'sign',
  Verify = 'verify',
  Encrypt = 'encrypt',
  Decrypt = 'decrypt',
  WrapKey = 'wrapKey',
  UnwrapKey = 'unwrapKey',
  DeriveKey = 'deriveKey',
  DeriveBits = 'deriveBits',
}
