/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JWKIssuerDN } from './jWKIssuerDN';
import { JWKPublicKey } from './jWKPublicKey';
import { JWKSubjectX500Principal } from './jWKSubjectX500Principal';

export interface JWKParsedX509CertChain {
  type?: string;
  subjectX500Principal?: JWKSubjectX500Principal;
  issuerX500Principal?: JWKSubjectX500Principal;
  version?: number;
  extendedKeyUsage?: Array<string>;
  issuerDN?: JWKIssuerDN;
  serialNumber?: number;
  tbscertificate?: Array<string>;
  signature?: Array<string>;
  basicConstraints?: number;
  issuerAlternativeNames?: Array<Array<unknown>>;
  issuerUniqueID?: Array<boolean>;
  keyUsage?: Array<boolean>;
  notAfter?: string;
  notBefore?: string;
  sigAlgName?: string;
  sigAlgOID?: string;
  sigAlgParams?: Array<string>;
  subjectAlternativeNames?: Array<Array<unknown>>;
  subjectDN?: JWKIssuerDN;
  subjectUniqueID?: Array<boolean>;
  criticalExtensionOIDs?: Array<string>;
  nonCriticalExtensionOIDs?: Array<string>;
  encoded?: Array<string>;
  publicKey?: JWKPublicKey;
}
