/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceUrls } from './serviceUrls';
import { DataController } from '../dataController';
import { ServiceProvider } from './serviceProvider';
import { ServiceCertificate } from './serviceCertificate';

export interface ServiceInstance {
  serviceProvider?: ServiceProvider;
  cert?: ServiceCertificate;
  serviceUrls?: ServiceUrls;
  dataController?: DataController;
  isBackendLinking?: boolean;
}
