/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceLinkRecordPayload } from './serviceLinkRecordPayload';
import { JWSHeader } from './jWSHeader';

export interface ServiceLinkRecordAccountSigned {
  payload: ServiceLinkRecordPayload;
  header: JWSHeader;
  signature: unknown;
  _protected: unknown;
}
