/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RSAKey } from '../service-linking/rSAKey';
import { ServicePopKey } from '../service-linking/servicePopKey';
import { SinkUsageRules } from './sinkUsageRules';

export interface ConsentRecordRoleSpecificPart {
  type: string;

  /* SINK CASE */
  usage_rules?: SinkUsageRules;
  source_cr_id?: string;

  /* SOURCE CASE */
  pop_key?: ServicePopKey;
  token_issuer_key?: RSAKey;
}
