/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RoleEnum } from '../service-linking/serviceEntry';

export interface ConsentFormRequest {
  /**
   * Surrogate Id related to Service initiating the Consenting request (can be either the Sink or, if any (in case of 3rd party re-use case) the Source service.
   */
  requester_surrogate_id: string;
  /**
   * Role (SINK, SOURCE) of requester Service initiating the Consenting request (is the Service related to the input Surrogate Id
   */
  requester_role: RoleEnum;
  /**
   * Purpose Id of Processing Bases described in the (Sink) Service Description.
   */
  purpose_id: string;
  /**
   * Id of the Service being part of the Consent as Sink party (3rd party) or Service processing data within itself.
   */
  sink_service_id: string;
  /**
   * Id of the Service being part of the Consent as Source party (if any, in case of 3rd party re-use case.
   */
  source_service_id?: string;
  /**
   * Dataset Id of the Source Service whose Data Mappings will be matched with the ones of datasets required by Sink Processing Bases (Purpose required datasets). In the within Service case, the processed Datasets are directly the ones required by Sink Processing Bases (Purpose).
   */
  source_service_dataset_id?: string;
}
