/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JOSEObjectType } from './jOSEObjectType';
import { JWSAlgorithm } from './jWSAlgorithm';
import { JWK } from './jWK';

export interface JWSHeader {
  customParams?: { [key: string]: object };
  parsedBase64URL?: object;
  jwk?: JWK;
  algorithm?: JWSAlgorithm;
  keyID?: string;
  x509CertURL?: string;
  x509CertChain?: Array<object>;
  jwkurl?: string;
  includedParams?: Array<string>;
  x509CertThumbprint?: object;
  x509CertSHA256Thumbprint?: object;
  type?: JOSEObjectType;
  contentType?: string;
  criticalParams?: Array<string>;
}
