/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyType } from './keyType';
import { KeyUse } from './keyUse';
import { Algorithm } from './algorithm';
import { JWKKeyStore } from './jWKKeyStore';
import { JWKParsedX509CertChain } from './jWKParsedX509CertChain';
import { OtherPrimesInfo } from './otherPrimesInfo';
import { KeyOperationsEnum } from './jWK';

export interface RSAKey {
  keyStore?: JWKKeyStore;
  _private?: boolean;
  modulus?: Record<string, unknown>;
  privateExponent?: Record<string, unknown>;
  publicExponent?: Record<string, unknown>;
  otherPrimes?: Array<OtherPrimesInfo>;
  secondPrimeFactor?: Record<string, unknown>;
  firstFactorCRTExponent?: Record<string, unknown>;
  firstCRTCoefficient?: Record<string, unknown>;
  secondFactorCRTExponent?: Record<string, unknown>;
  firstPrimeFactor?: Record<string, unknown>;
  requiredParams?: { [key: string]: Record<string, unknown> };
  algorithm?: Algorithm;
  keyID?: string;
  keyType?: KeyType;
  keyUse?: KeyUse;
  keyOperations?: Array<KeyOperationsEnum>;
  x509CertURL?: string;
  x509CertChain?: Array<Record<string, unknown>>;
  parsedX509CertChain?: Array<JWKParsedX509CertChain>;
  x509CertThumbprint?: Record<string, unknown>;
  x509CertSHA256Thumbprint?: Record<string, unknown>;
}
