/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServicePopKey } from './servicePopKey';
import { RSAKey } from './rSAKey';

export interface ServiceLinkRecordPayload {
  iat: string;
  version: string;
  link_id: string;
  operator_id: string;
  service_id: string;
  service_uri: string;
  service_name: string;
  pop_key?: ServicePopKey;
  service_description_version: string;
  surrogate_id: string;
  operator_key: RSAKey;
  cr_keys?: Array<RSAKey>;
  account_id: string;
  username: string;
}
