version: '3.8'
services:
  cape-playground:
    image: capesuite/cape-playground
    build:
      context: .
      args:
        BASE_HREF: /cape-playground/
    ports:
      - '82:80'
    volumes:
      - ./src/assets/config.prod.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cape-network

networks:
  cape-network:
    name: cape-playground-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
