/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Storage {
  location?: LocationEnum;
  duration?: DurationEnum;
}
export enum LocationEnum {
  ControllerServers = 'Controller servers',
  Eu = 'Eu',
  ThirdCountries = 'Third countries',
  OurServers = 'Our servers',
  ProcessorServers = 'Processor servers',
  ThirdParty = 'Third party'
}
export enum DurationEnum {
  BusinessPractices = 'Business practices',
  LegalRequirement = 'Legal requirement',
  StatedPurpose = 'Stated purpose',
  Indefinitely = 'Indefinitely'
}


