/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';
import { ShareWith } from '../shareWith';
import { Storage } from '../storage';
import { Obligation } from '../obligation';


export interface SinkUsageRules {
  purposeId: string;
  purposeCategory: string;
  legalBasis: SinkUsageRulesLegalBasis;
  purposeName: string;
  processingCategories: Array<SinkUsageRulesProcessingCategories>;
  policy: Policy;
  storage?: Storage;
  recipients?: Array<SinkUsageRulesRecipients>;
  shareWith?: Array<ShareWith>;
  obligations?: Array<Obligation>;
  collectionMethod?: string;
  termination?: string;
}
export enum SinkUsageRulesLegalBasis {
  Consent = 'Consent',
  Contract = 'Contract',
  LegalObligation = 'Legal obligation',
  VitalInterest = 'Vital interest',
  PublicInterest = 'Public interest',
  LegitimateInterest = 'Legitimate interest'
};
export enum SinkUsageRulesProcessingCategories {
  Aggregate = 'Aggregate',
  Analyse = 'Analyse',
  Anonymize = 'Anonymize',
  Collect = 'Collect',
  Copy = 'Copy',
  Derive = 'Derive',
  Move = 'Move',
  Query = 'Query',
  Transfer = 'Transfer'
};
export enum SinkUsageRulesRecipients {
  Ours = 'Ours',
  Delivery = 'Delivery',
  Same = 'Same',
  OtherRecipient = 'Other recipient',
  Unrelated = 'Unrelated',
  Public = 'Public'
};



