version: "3.8"
services:

  service-sdk:
    image: capesuite/service-sdk
    build: ./
    ports:
      - "8085:8085"
    environment:
      #- PROFILE=
      - APIDOCS_PATH=/api-docs
#      - SPRING_LOGGING_LEVEL=DEBUG
#      - MONGO_LOGGING_LEVEL=DEBUG
#      - SECURITY_LOGGING_LEVEL=DEBUG
#      - CAPE_LOGGING_LEVEL=DEBUG
      - CAPE_ACCOUNT_MANAGER_URL=http://account-manager:8080/account-manager
      - CAPE_SERVICE_MANAGER_URL=http://service-manager:8082/service-manager
      - CAPE_SERVICE_REGISTRY_URL=http://service-registry:8088/service-registry
      - CAPE_CONSENT_MANAGER_URL=http://consent-manager:8083/consent-manager
      - CAPE_SERVICESDK_BUSINESS_ID=ENG
      - CAPE_SDK_MONGODB_HOST=service-sdk-mongo
      - CAPE_SDK_MONGODB_PORT=27017
      - CAPE_SDK_MONGODB_USER=root
      - CAPE_SDK_MONGODB_PASSWORD=root
      - CAPE_IDM_HOST=https://www.cape-suite.eu:8002
      - CAPE_IDM_CLIENTID=1c0407c2-b7ee-4117-8a99-c20b3a964cc1
      - CAPE_IDM_CLIENTSECRET=be308970-4f1b-4990-926a-987c948c462f
      - CAPE_IDM_USERINFOURI=https://www.cape-suite.eu:8002/user
    networks:
      - cape-sdk-network
  service-sdk-mongo:
    image: mongo:4.2
    restart: always
    ports:
     - "27025:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: service-sdk-volume
        target: /data/db
        volume:
          nocopy: true  
    networks:
      - cape-sdk-network

volumes:
  service-sdk-volume:

networks:
 cape-sdk-network:
    external:
      name: cape-server-network