#-------------------------------------------------------------------------------
# CaPe - A Consent Based Personal Data Suite
#  Copyright (C) 2021 Engineering Ingegneria Informatica S.p.A.
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
version: "3.8"
services:

  service-sdk:
    image: capesuite/service-sdk
    build: ./
    ports:
      - "8085:8085"
    environment:
      #- PROFILE=
      - APIDOCS_PATH=/api-docs
      - SPRING_LOGGING_LEVEL=INFO
      - MONGO_LOGGING_LEVEL=ERROR
      - SECURITY_LOGGING_LEVEL=DEBUG
      - CAPE_LOGGING_LEVEL=ERROR
      - CAPE_ACCOUNT_MANAGER_URL=http://account-manager:8080/account-manager
      - CAPE_SERVICE_MANAGER_URL=http://service-manager:8082/service-manager
      - CAPE_SERVICE_REGISTRY_URL=http://service-registry:8088/service-registry
      - CAPE_CONSENT_MANAGER_URL=http://consent-manager:8083/consent-manager
      - CAPE_SERVICESDK_BUSINESS_ID=ENG
      - CAPE_SDK_MONGODB_HOST=service-sdk-mongo
      - CAPE_SDK_MONGODB_PORT=27017
      - CAPE_SDK_MONGODB_USER=root
      - CAPE_SDK_MONGODB_PASSWORD=root
      - CAPE_ENABLE_AUTH=false
      - CAPE_IDM_ISSUER_URI=http://host.docker.internal:8099/auth/realms/Cape
      - CAPE_IDM_ALLOWED_ORIGIN_PATTERNS=http://localhost:81,http://localhost,http://localhost:82,http://localhost:83
      - CAPE_IDM_ALLOWED_ORIGINS=
    networks:
      - cape-sdk-network
  service-sdk-mongo:
    image: mongo:4.4.6
    restart: always
    ports:
     - "27025:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: service-sdk-volume
        target: /data/db
        volume:
          nocopy: true  
    networks:
      - cape-sdk-network

volumes:
  service-sdk-volume:

networks:
 cape-sdk-network:
    external:
      name: cape-server-network
