/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Description2 } from './service-link/description2';
import { ShareWith } from './shareWith';
import { Storage } from './storage';
import { Obligation } from './obligation';


export interface ProcessingBasis {
  purposeId?: string;
  purposeName?: string;
  legalBasis?: LegalBasisEnum;
  purposeCategory?: string;
  processingCategories?: Array<ProcessingCategoriesEnum>;
  description?: Array<Description2>;
  requiredDatasets?: Array<string>;
  storage?: Storage;
  recipients?: Array<RecipientsEnum>;
  shareWith?: Array<ShareWith>;
  obligations?: Array<Obligation>;
  policyRef?: string;
  collectionMethod?: string;
  termination?: string;
}

export enum LegalBasisEnum {
  Consent = 'Consent',
  Contract = 'Contract',
  LegalObligation = 'Legal obligation',
  VitalInterest = 'Vital interest',
  PublicInterest = 'Public interest',
  LegitimateInterest = 'Legitimate interest'
}
export enum ProcessingCategoriesEnum {
  Aggregate = 'Aggregate',
  Analyse = 'Analyse',
  Anonymize = 'Anonymize',
  Collect = 'Collect',
  Copy = 'Copy',
  Derive = 'Derive',
  Move = 'Move',
  Query = 'Query',
  Transfer = 'Transfer'
}

export enum RecipientsEnum {
  Ours = 'Ours',
  Delivery = 'Delivery',
  Same = 'Same',
  OtherRecipient = 'Other recipient',
  Unrelated = 'Unrelated',
  Public = 'Public'
}


