/**
 * SDK Service API
 * SDK Service API for integration with cape
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyType } from './keyType';
import { KeyUse } from './keyUse';
import { Algorithm } from './algorithm';
import { JWKKeyStore } from './jWKKeyStore';
import { JWKParsedX509CertChain } from './jWKParsedX509CertChain';
import { OtherPrimesInfo } from './otherPrimesInfo';


export interface RSAKey {
  keyStore?: JWKKeyStore;
  _private?: boolean;
  modulus?: object;
  privateExponent?: object;
  publicExponent?: object;
  otherPrimes?: Array<OtherPrimesInfo>;
  secondPrimeFactor?: object;
  firstFactorCRTExponent?: object;
  firstCRTCoefficient?: object;
  secondFactorCRTExponent?: object;
  firstPrimeFactor?: object;
  requiredParams?: { [key: string]: object; };
  algorithm?: Algorithm;
  keyID?: string;
  keyType?: KeyType;
  keyUse?: KeyUse;
  keyOperations?: Array<KeyOperationsEnum>;
  x509CertURL?: string;
  x509CertChain?: Array<object>;
  parsedX509CertChain?: Array<JWKParsedX509CertChain>;
  x509CertThumbprint?: object;
  x509CertSHA256Thumbprint?: object;
}
export enum KeyOperationsEnum {
  Sign = 'sign',
  Verify = 'verify',
  Encrypt = 'encrypt',
  Decrypt = 'decrypt',
  WrapKey = 'wrapKey',
  UnwrapKey = 'unwrapKey',
  DeriveKey = 'deriveKey',
  DeriveBits = 'deriveBits'
}


