# base image
FROM node:12.9.0-alpine

RUN mkdir -p /app
# set working directory
WORKDIR /app


# install and cache app dependencies
COPY package.json /app

RUN npm install
RUN npm install -g @angular/cli@10.1.3

# add app
COPY . /app

# start app
CMD ng serve --host 0.0.0.0